amout:
  #普通freeは変更しないよね？
  FREE: 0
  #lightプランは18スタック入るゾ
  LIGHT: 100
  #MIDDLEプランは27スタック入るゾ つまり普通のチェストだゾ
  MIDDLE: 300
  #LARGEプランは54スタック入るゾ つまりラージチェストだゾ
  LARGE: 500
  #unitのところにお金の単位を入れてください。（Vaultがお金の単位をこっちにAPIとしてよこしてくれないんだよクソが）
unit: "FP"